// <auto-generated>
/*
 * dofusdude
 *
 * # Open Ankama Developer Community The all-in-one toolbelt for your next Ankama related project.  ## Versions - [Dofus 2](https://docs.dofusdu.de/dofus2/) - [Dofus 3](https://docs.dofusdu.de/dofus3/)   - v1 [latest] (you are here)   ## Client SDKs - [Javascript](https://github.com/dofusdude/dofusdude-js) `npm i dofusdude-js - -save` - [Typescript](https://github.com/dofusdude/dofusdude-ts) `npm i dofusdude-ts - -save` - [Go](https://github.com/dofusdude/dodugo) `go get -u github.com/dofusdude/dodugo` - [Python](https://github.com/dofusdude/dofusdude-py) `pip install dofusdude` - [Java](https://github.com/dofusdude/dofusdude-java) Maven with GitHub packages setup  Everything, including this site, is generated out of the [Docs Repo](https://github.com/dofusdude/api-docs). Consider it the Single Source of Truth. If there is a problem with the SDKs, create an issue there.  Your favorite language is missing? Please let me know!  # Main Features - 🥷 **Seamless Auto-Update** load data in the background when a new Dofus version is released and serving it within 10 minutes with atomic data source switching. No downtime and no effects for the user, just always up-to-date.  - ⚡ **Blazingly Fast** all data in-memory, aggressive caching over short time spans, HTTP/2 multiplexing, written in Go, optimized for low latency, hosted on bare metal in 🇩🇪.  - 📨 **Almanax Discord Integration** Use the endpoints as a dev or the official [Web Client](https://discord.dofusdude.com) as a user.  - 🩸 **Dofus 3 Beta** from stable to bleeding edge by replacing /dofus3 with /dofus3beta.  - 🗣️ **Multilingual** supporting _en_, _fr_, _es_, _pt_, _de_.  - 🧠 **Search by Relevance** allowing typos in name and description, handled by language specific text analysis and indexing.  - 🕵️ **Official Sources** generated from actual data from the game.  ... and much more on the Roadmap on my [Discord](https://discord.gg/3EtHskZD8h). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: stelzo@steado.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Dofusdude.Api.Client;

namespace Dofusdude.Api.Model
{
    /// <summary>
    /// ConditionRelation
    /// </summary>
    public partial class ConditionRelation : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConditionRelation" /> class.
        /// </summary>
        /// <param name="isOperand">always \&quot;false\&quot; for relations (default to false)</param>
        /// <param name="relation">\&quot;and\&quot;, \&quot;or\&quot; (default to &quot;and&quot;)</param>
        /// <param name="children">children</param>
        [JsonConstructor]
        public ConditionRelation(Option<bool?> isOperand = default, Option<string?> relation = default, Option<List<ConditionNode>?> children = default)
        {
            IsOperandOption = isOperand;
            RelationOption = relation;
            ChildrenOption = children;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of IsOperand
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsOperandOption { get; private set; }

        /// <summary>
        /// always \&quot;false\&quot; for relations
        /// </summary>
        /// <value>always \&quot;false\&quot; for relations</value>
        [JsonPropertyName("is_operand")]
        public bool? IsOperand { get { return this.IsOperandOption; } set { this.IsOperandOption = new(value); } }

        /// <summary>
        /// Used to track the state of Relation
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RelationOption { get; private set; }

        /// <summary>
        /// \&quot;and\&quot;, \&quot;or\&quot;
        /// </summary>
        /// <value>\&quot;and\&quot;, \&quot;or\&quot;</value>
        /* <example>and</example> */
        [JsonPropertyName("relation")]
        public string? Relation { get { return this.RelationOption; } set { this.RelationOption = new(value); } }

        /// <summary>
        /// Used to track the state of Children
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ConditionNode>?> ChildrenOption { get; private set; }

        /// <summary>
        /// Gets or Sets Children
        /// </summary>
        [JsonPropertyName("children")]
        public List<ConditionNode>? Children { get { return this.ChildrenOption; } set { this.ChildrenOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConditionRelation {\n");
            sb.Append("  IsOperand: ").Append(IsOperand).Append("\n");
            sb.Append("  Relation: ").Append(Relation).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ConditionRelation" />
    /// </summary>
    public class ConditionRelationJsonConverter : JsonConverter<ConditionRelation>
    {
        /// <summary>
        /// Deserializes json to <see cref="ConditionRelation" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ConditionRelation Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<bool?> isOperand = default;
            Option<string?> relation = default;
            Option<List<ConditionNode>?> children = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "is_operand":
                            isOperand = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        case "relation":
                            relation = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "children":
                            children = new Option<List<ConditionNode>?>(JsonSerializer.Deserialize<List<ConditionNode>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (isOperand.IsSet && isOperand.Value == null)
                throw new ArgumentNullException(nameof(isOperand), "Property is not nullable for class ConditionRelation.");

            if (relation.IsSet && relation.Value == null)
                throw new ArgumentNullException(nameof(relation), "Property is not nullable for class ConditionRelation.");

            if (children.IsSet && children.Value == null)
                throw new ArgumentNullException(nameof(children), "Property is not nullable for class ConditionRelation.");

            return new ConditionRelation(isOperand, relation, children);
        }

        /// <summary>
        /// Serializes a <see cref="ConditionRelation" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="conditionRelation"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ConditionRelation conditionRelation, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, conditionRelation, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ConditionRelation" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="conditionRelation"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ConditionRelation conditionRelation, JsonSerializerOptions jsonSerializerOptions)
        {
            if (conditionRelation.RelationOption.IsSet && conditionRelation.Relation == null)
                throw new ArgumentNullException(nameof(conditionRelation.Relation), "Property is required for class ConditionRelation.");

            if (conditionRelation.ChildrenOption.IsSet && conditionRelation.Children == null)
                throw new ArgumentNullException(nameof(conditionRelation.Children), "Property is required for class ConditionRelation.");

            if (conditionRelation.IsOperandOption.IsSet)
                writer.WriteBoolean("is_operand", conditionRelation.IsOperandOption.Value!.Value);

            if (conditionRelation.RelationOption.IsSet)
                writer.WriteString("relation", conditionRelation.Relation);

            if (conditionRelation.ChildrenOption.IsSet)
            {
                writer.WritePropertyName("children");
                JsonSerializer.Serialize(writer, conditionRelation.Children, jsonSerializerOptions);
            }
        }
    }
}
