// <auto-generated>
/*
 * dofusdude
 *
 * # Open Ankama Developer Community The all-in-one toolbelt for your next Ankama related project.  ## Versions - [Dofus 2](https://docs.dofusdu.de/dofus2/) - [Dofus 3](https://docs.dofusdu.de/dofus3/)   - v1 [latest] (you are here)   ## Client SDKs - [Javascript](https://github.com/dofusdude/dofusdude-js) `npm i dofusdude-js - -save` - [Typescript](https://github.com/dofusdude/dofusdude-ts) `npm i dofusdude-ts - -save` - [Go](https://github.com/dofusdude/dodugo) `go get -u github.com/dofusdude/dodugo` - [Python](https://github.com/dofusdude/dofusdude-py) `pip install dofusdude` - [Java](https://github.com/dofusdude/dofusdude-java) Maven with GitHub packages setup  Everything, including this site, is generated out of the [Docs Repo](https://github.com/dofusdude/api-docs). Consider it the Single Source of Truth. If there is a problem with the SDKs, create an issue there.  Your favorite language is missing? Please let me know!  # Main Features - 🥷 **Seamless Auto-Update** load data in the background when a new Dofus version is released and serving it within 10 minutes with atomic data source switching. No downtime and no effects for the user, just always up-to-date.  - ⚡ **Blazingly Fast** all data in-memory, aggressive caching over short time spans, HTTP/2 multiplexing, written in Go, optimized for low latency, hosted on bare metal in 🇩🇪.  - 📨 **Almanax Discord Integration** Use the endpoints as a dev or the official [Web Client](https://discord.dofusdude.com) as a user.  - 🩸 **Dofus 3 Beta** from stable to bleeding edge by replacing /dofus3 with /dofus3beta.  - 🗣️ **Multilingual** supporting _en_, _fr_, _es_, _pt_, _de_.  - 🧠 **Search by Relevance** allowing typos in name and description, handled by language specific text analysis and indexing.  - 🕵️ **Official Sources** generated from actual data from the game.  ... and much more on the Roadmap on my [Discord](https://discord.gg/3EtHskZD8h). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: stelzo@steado.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Dofusdude.Api.Client;

namespace Dofusdude.Api.Model
{
    /// <summary>
    /// ListEquipmentSets
    /// </summary>
    public partial class ListEquipmentSets : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListEquipmentSets" /> class.
        /// </summary>
        /// <param name="links">links</param>
        /// <param name="sets">sets</param>
        [JsonConstructor]
        public ListEquipmentSets(Option<PagedLinks?> links = default, Option<List<ListEquipmentSet>?> sets = default)
        {
            LinksOption = links;
            SetsOption = sets;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Links
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PagedLinks?> LinksOption { get; private set; }

        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [JsonPropertyName("_links")]
        public PagedLinks? Links { get { return this.LinksOption; } set { this.LinksOption = new(value); } }

        /// <summary>
        /// Used to track the state of Sets
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ListEquipmentSet>?> SetsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Sets
        /// </summary>
        [JsonPropertyName("sets")]
        public List<ListEquipmentSet>? Sets { get { return this.SetsOption; } set { this.SetsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ListEquipmentSets {\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  Sets: ").Append(Sets).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ListEquipmentSets" />
    /// </summary>
    public class ListEquipmentSetsJsonConverter : JsonConverter<ListEquipmentSets>
    {
        /// <summary>
        /// Deserializes json to <see cref="ListEquipmentSets" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ListEquipmentSets Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<PagedLinks?> links = default;
            Option<List<ListEquipmentSet>?> sets = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "_links":
                            links = new Option<PagedLinks?>(JsonSerializer.Deserialize<PagedLinks>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "sets":
                            sets = new Option<List<ListEquipmentSet>?>(JsonSerializer.Deserialize<List<ListEquipmentSet>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (links.IsSet && links.Value == null)
                throw new ArgumentNullException(nameof(links), "Property is not nullable for class ListEquipmentSets.");

            if (sets.IsSet && sets.Value == null)
                throw new ArgumentNullException(nameof(sets), "Property is not nullable for class ListEquipmentSets.");

            return new ListEquipmentSets(links, sets);
        }

        /// <summary>
        /// Serializes a <see cref="ListEquipmentSets" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listEquipmentSets"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ListEquipmentSets listEquipmentSets, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, listEquipmentSets, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ListEquipmentSets" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="listEquipmentSets"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ListEquipmentSets listEquipmentSets, JsonSerializerOptions jsonSerializerOptions)
        {
            if (listEquipmentSets.LinksOption.IsSet && listEquipmentSets.Links == null)
                throw new ArgumentNullException(nameof(listEquipmentSets.Links), "Property is required for class ListEquipmentSets.");

            if (listEquipmentSets.SetsOption.IsSet && listEquipmentSets.Sets == null)
                throw new ArgumentNullException(nameof(listEquipmentSets.Sets), "Property is required for class ListEquipmentSets.");

            if (listEquipmentSets.LinksOption.IsSet)
            {
                writer.WritePropertyName("_links");
                JsonSerializer.Serialize(writer, listEquipmentSets.Links, jsonSerializerOptions);
            }
            if (listEquipmentSets.SetsOption.IsSet)
            {
                writer.WritePropertyName("sets");
                JsonSerializer.Serialize(writer, listEquipmentSets.Sets, jsonSerializerOptions);
            }
        }
    }
}
