// <auto-generated>
/*
 * dofusdude
 *
 * # Open Ankama Developer Community The all-in-one toolbelt for your next Ankama related project.  ## Versions - [Dofus 2](https://docs.dofusdu.de/dofus2/) - [Dofus 3](https://docs.dofusdu.de/dofus3/)   - v1 [latest] (you are here)   ## Client SDKs - [Javascript](https://github.com/dofusdude/dofusdude-js) `npm i dofusdude-js - -save` - [Typescript](https://github.com/dofusdude/dofusdude-ts) `npm i dofusdude-ts - -save` - [Go](https://github.com/dofusdude/dodugo) `go get -u github.com/dofusdude/dodugo` - [Python](https://github.com/dofusdude/dofusdude-py) `pip install dofusdude` - [Java](https://github.com/dofusdude/dofusdude-java) Maven with GitHub packages setup  Everything, including this site, is generated out of the [Docs Repo](https://github.com/dofusdude/api-docs). Consider it the Single Source of Truth. If there is a problem with the SDKs, create an issue there.  Your favorite language is missing? Please let me know!  # Main Features - 🥷 **Seamless Auto-Update** load data in the background when a new Dofus version is released and serving it within 10 minutes with atomic data source switching. No downtime and no effects for the user, just always up-to-date.  - ⚡ **Blazingly Fast** all data in-memory, aggressive caching over short time spans, HTTP/2 multiplexing, written in Go, optimized for low latency, hosted on bare metal in 🇩🇪.  - 📨 **Almanax Discord Integration** Use the endpoints as a dev or the official [Web Client](https://discord.dofusdude.com) as a user.  - 🩸 **Dofus 3 Beta** from stable to bleeding edge by replacing /dofus3 with /dofus3beta.  - 🗣️ **Multilingual** supporting _en_, _fr_, _es_, _pt_, _de_.  - 🧠 **Search by Relevance** allowing typos in name and description, handled by language specific text analysis and indexing.  - 🕵️ **Official Sources** generated from actual data from the game.  ... and much more on the Roadmap on my [Discord](https://discord.gg/3EtHskZD8h). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: stelzo@steado.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Dofusdude.Api.Client;

namespace Dofusdude.Api.Model
{
    /// <summary>
    /// Mount
    /// </summary>
    public partial class Mount : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Mount" /> class.
        /// </summary>
        /// <param name="ankamaId">ankamaId</param>
        /// <param name="name">name</param>
        /// <param name="family">family</param>
        /// <param name="imageUrls">imageUrls</param>
        /// <param name="effects">effects</param>
        [JsonConstructor]
        public Mount(Option<int?> ankamaId = default, Option<string?> name = default, Option<MountFamily?> family = default, Option<Images?> imageUrls = default, Option<List<Effect>?> effects = default)
        {
            AnkamaIdOption = ankamaId;
            NameOption = name;
            FamilyOption = family;
            ImageUrlsOption = imageUrls;
            EffectsOption = effects;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of AnkamaId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> AnkamaIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets AnkamaId
        /// </summary>
        [JsonPropertyName("ankama_id")]
        public int? AnkamaId { get { return this.AnkamaIdOption; } set { this.AnkamaIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Family
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MountFamily?> FamilyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Family
        /// </summary>
        [JsonPropertyName("family")]
        public MountFamily? Family { get { return this.FamilyOption; } set { this.FamilyOption = new(value); } }

        /// <summary>
        /// Used to track the state of ImageUrls
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Images?> ImageUrlsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ImageUrls
        /// </summary>
        [JsonPropertyName("image_urls")]
        public Images? ImageUrls { get { return this.ImageUrlsOption; } set { this.ImageUrlsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Effects
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Effect>?> EffectsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Effects
        /// </summary>
        [JsonPropertyName("effects")]
        public List<Effect>? Effects { get { return this.EffectsOption; } set { this.EffectsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Mount {\n");
            sb.Append("  AnkamaId: ").Append(AnkamaId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Family: ").Append(Family).Append("\n");
            sb.Append("  ImageUrls: ").Append(ImageUrls).Append("\n");
            sb.Append("  Effects: ").Append(Effects).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Mount" />
    /// </summary>
    public class MountJsonConverter : JsonConverter<Mount>
    {
        /// <summary>
        /// Deserializes json to <see cref="Mount" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Mount Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> ankamaId = default;
            Option<string?> name = default;
            Option<MountFamily?> family = default;
            Option<Images?> imageUrls = default;
            Option<List<Effect>?> effects = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "ankama_id":
                            ankamaId = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "family":
                            family = new Option<MountFamily?>(JsonSerializer.Deserialize<MountFamily>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "image_urls":
                            imageUrls = new Option<Images?>(JsonSerializer.Deserialize<Images>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "effects":
                            effects = new Option<List<Effect>?>(JsonSerializer.Deserialize<List<Effect>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (ankamaId.IsSet && ankamaId.Value == null)
                throw new ArgumentNullException(nameof(ankamaId), "Property is not nullable for class Mount.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Mount.");

            if (family.IsSet && family.Value == null)
                throw new ArgumentNullException(nameof(family), "Property is not nullable for class Mount.");

            if (imageUrls.IsSet && imageUrls.Value == null)
                throw new ArgumentNullException(nameof(imageUrls), "Property is not nullable for class Mount.");

            return new Mount(ankamaId, name, family, imageUrls, effects);
        }

        /// <summary>
        /// Serializes a <see cref="Mount" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mount"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Mount mount, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, mount, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Mount" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="mount"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Mount mount, JsonSerializerOptions jsonSerializerOptions)
        {
            if (mount.NameOption.IsSet && mount.Name == null)
                throw new ArgumentNullException(nameof(mount.Name), "Property is required for class Mount.");

            if (mount.FamilyOption.IsSet && mount.Family == null)
                throw new ArgumentNullException(nameof(mount.Family), "Property is required for class Mount.");

            if (mount.ImageUrlsOption.IsSet && mount.ImageUrls == null)
                throw new ArgumentNullException(nameof(mount.ImageUrls), "Property is required for class Mount.");

            if (mount.AnkamaIdOption.IsSet)
                writer.WriteNumber("ankama_id", mount.AnkamaIdOption.Value!.Value);

            if (mount.NameOption.IsSet)
                writer.WriteString("name", mount.Name);

            if (mount.FamilyOption.IsSet)
            {
                writer.WritePropertyName("family");
                JsonSerializer.Serialize(writer, mount.Family, jsonSerializerOptions);
            }
            if (mount.ImageUrlsOption.IsSet)
            {
                writer.WritePropertyName("image_urls");
                JsonSerializer.Serialize(writer, mount.ImageUrls, jsonSerializerOptions);
            }
            if (mount.EffectsOption.IsSet)
                if (mount.EffectsOption.Value != null)
                {
                    writer.WritePropertyName("effects");
                    JsonSerializer.Serialize(writer, mount.Effects, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("effects");
        }
    }
}
