// <auto-generated>
/*
 * dofusdude
 *
 * # Open Ankama Developer Community The all-in-one toolbelt for your next Ankama related project.  ## Versions - [Dofus 2](https://docs.dofusdu.de/dofus2/) - [Dofus 3](https://docs.dofusdu.de/dofus3/)   - v1 [latest] (you are here)   ## Client SDKs - [Javascript](https://github.com/dofusdude/dofusdude-js) `npm i dofusdude-js - -save` - [Typescript](https://github.com/dofusdude/dofusdude-ts) `npm i dofusdude-ts - -save` - [Go](https://github.com/dofusdude/dodugo) `go get -u github.com/dofusdude/dodugo` - [Python](https://github.com/dofusdude/dofusdude-py) `pip install dofusdude` - [Java](https://github.com/dofusdude/dofusdude-java) Maven with GitHub packages setup  Everything, including this site, is generated out of the [Docs Repo](https://github.com/dofusdude/api-docs). Consider it the Single Source of Truth. If there is a problem with the SDKs, create an issue there.  Your favorite language is missing? Please let me know!  # Main Features - 🥷 **Seamless Auto-Update** load data in the background when a new Dofus version is released and serving it within 10 minutes with atomic data source switching. No downtime and no effects for the user, just always up-to-date.  - ⚡ **Blazingly Fast** all data in-memory, aggressive caching over short time spans, HTTP/2 multiplexing, written in Go, optimized for low latency, hosted on bare metal in 🇩🇪.  - 📨 **Almanax Discord Integration** Use the endpoints as a dev or the official [Web Client](https://discord.dofusdude.com) as a user.  - 🩸 **Dofus 3 Beta** from stable to bleeding edge by replacing /dofus3 with /dofus3beta.  - 🗣️ **Multilingual** supporting _en_, _fr_, _es_, _pt_, _de_.  - 🧠 **Search by Relevance** allowing typos in name and description, handled by language specific text analysis and indexing.  - 🕵️ **Official Sources** generated from actual data from the game.  ... and much more on the Roadmap on my [Discord](https://discord.gg/3EtHskZD8h). 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: stelzo@steado.de
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Dofusdude.Api.Client;
using Dofusdude.Api.Model;
using System.Diagnostics.CodeAnalysis;

namespace Dofusdude.Api.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IGameApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        GameApiEvents Events { get; }

        /// <summary>
        /// Game Search
        /// </summary>
        /// <remarks>
        /// Search in all names and descriptions of all supported types in the game. For the list of supported types see the endpoint /dofus3/meta/search/types.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="language">a valid language code</param>
        /// <param name="game">game main &#39;dofus3&#39; or beta channel &#39;dofus3beta&#39;</param>
        /// <param name="query">search query</param>
        /// <param name="filterSearchIndex">only results with all specific type (optional)</param>
        /// <param name="limit">maximum number of returned results (optional, default to 8)</param>
        /// <param name="fieldsItem">adds fields from the item search to the list entries if the hit is an item. Multiple comma separated values allowed. (optional)</param>
        /// <param name="filterTypeNameId">multi-filter results with the english item type name, including \&quot;mount\&quot; and \&quot;set\&quot; from filter[search_index]. Add with \&quot;wood\&quot; or \&quot;+wood\&quot; and exclude with \&quot;-wood\&quot;. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetGameSearchApiResponse"/>&gt;</returns>
        Task<IGetGameSearchApiResponse> GetGameSearchAsync(string language, string game, string query, Option<List<string>> filterSearchIndex = default, Option<int> limit = default, Option<List<string>> fieldsItem = default, Option<List<string>> filterTypeNameId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Game Search
        /// </summary>
        /// <remarks>
        /// Search in all names and descriptions of all supported types in the game. For the list of supported types see the endpoint /dofus3/meta/search/types.
        /// </remarks>
        /// <param name="language">a valid language code</param>
        /// <param name="game">game main &#39;dofus3&#39; or beta channel &#39;dofus3beta&#39;</param>
        /// <param name="query">search query</param>
        /// <param name="filterSearchIndex">only results with all specific type (optional)</param>
        /// <param name="limit">maximum number of returned results (optional, default to 8)</param>
        /// <param name="fieldsItem">adds fields from the item search to the list entries if the hit is an item. Multiple comma separated values allowed. (optional)</param>
        /// <param name="filterTypeNameId">multi-filter results with the english item type name, including \&quot;mount\&quot; and \&quot;set\&quot; from filter[search_index]. Add with \&quot;wood\&quot; or \&quot;+wood\&quot; and exclude with \&quot;-wood\&quot;. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetGameSearchApiResponse"/>?&gt;</returns>
        Task<IGetGameSearchApiResponse?> GetGameSearchOrDefaultAsync(string language, string game, string query, Option<List<string>> filterSearchIndex = default, Option<int> limit = default, Option<List<string>> fieldsItem = default, Option<List<string>> filterTypeNameId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Search All Items
        /// </summary>
        /// <remarks>
        /// Search in all names and descriptions of Dofus items (including all subtypes) with a query.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="language">a valid language code</param>
        /// <param name="game">game main &#39;dofus3&#39; or beta channel &#39;dofus3beta&#39;</param>
        /// <param name="query">case sensitive search query</param>
        /// <param name="filterMinLevel">only results which level is equal or above this value (optional)</param>
        /// <param name="filterMaxLevel">only results which level is equal or below this value (optional)</param>
        /// <param name="limit">maximum number of returned results (optional, default to 8)</param>
        /// <param name="filterTypeNameId">multi-filter results with the english type name. Add with \&quot;wood\&quot; or \&quot;+wood\&quot; and exclude with \&quot;-wood\&quot;. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetItemsAllSearchApiResponse"/>&gt;</returns>
        Task<IGetItemsAllSearchApiResponse> GetItemsAllSearchAsync(string language, string game, string query, Option<int> filterMinLevel = default, Option<int> filterMaxLevel = default, Option<int> limit = default, Option<List<string>> filterTypeNameId = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Search All Items
        /// </summary>
        /// <remarks>
        /// Search in all names and descriptions of Dofus items (including all subtypes) with a query.
        /// </remarks>
        /// <param name="language">a valid language code</param>
        /// <param name="game">game main &#39;dofus3&#39; or beta channel &#39;dofus3beta&#39;</param>
        /// <param name="query">case sensitive search query</param>
        /// <param name="filterMinLevel">only results which level is equal or above this value (optional)</param>
        /// <param name="filterMaxLevel">only results which level is equal or below this value (optional)</param>
        /// <param name="limit">maximum number of returned results (optional, default to 8)</param>
        /// <param name="filterTypeNameId">multi-filter results with the english type name. Add with \&quot;wood\&quot; or \&quot;+wood\&quot; and exclude with \&quot;-wood\&quot;. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetItemsAllSearchApiResponse"/>?&gt;</returns>
        Task<IGetItemsAllSearchApiResponse?> GetItemsAllSearchOrDefaultAsync(string language, string game, string query, Option<int> filterMinLevel = default, Option<int> filterMaxLevel = default, Option<int> limit = default, Option<List<string>> filterTypeNameId = default, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IGetGameSearchApiResponse"/>
    /// </summary>
    public interface IGetGameSearchApiResponse : Dofusdude.Api.Client.IApiResponse, IOk<List<GameSearch>?>, IBadRequest<Dofusdude.Api.Model.Error?>, INotFound<Dofusdude.Api.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }
    }

    /// <summary>
    /// The <see cref="IGetItemsAllSearchApiResponse"/>
    /// </summary>
    public interface IGetItemsAllSearchApiResponse : Dofusdude.Api.Client.IApiResponse, IOk<List<ListItemGeneral>?>, IBadRequest<Dofusdude.Api.Model.Error?>, INotFound<Dofusdude.Api.Model.Error?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class GameApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetGameSearch;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetGameSearch;

        internal void ExecuteOnGetGameSearch(GameApi.GetGameSearchApiResponse apiResponse)
        {
            OnGetGameSearch?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetGameSearch(Exception exception)
        {
            OnErrorGetGameSearch?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnGetItemsAllSearch;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorGetItemsAllSearch;

        internal void ExecuteOnGetItemsAllSearch(GameApi.GetItemsAllSearchApiResponse apiResponse)
        {
            OnGetItemsAllSearch?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorGetItemsAllSearch(Exception exception)
        {
            OnErrorGetItemsAllSearch?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class GameApi : IGameApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<GameApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public GameApiEvents Events { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="GameApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GameApi(ILogger<GameApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, GameApiEvents gameApiEvents)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<GameApi>();
            HttpClient = httpClient;
            Events = gameApiEvents;
        }

        partial void FormatGetGameSearch(ref string language, ref string game, ref string query, Option<List<string>> filterSearchIndex, ref Option<int> limit, Option<List<string>> fieldsItem, Option<List<string>> filterTypeNameId);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="language"></param>
        /// <param name="game"></param>
        /// <param name="query"></param>
        /// <param name="filterSearchIndex"></param>
        /// <param name="fieldsItem"></param>
        /// <param name="filterTypeNameId"></param>
        /// <returns></returns>
        private void ValidateGetGameSearch(string language, string game, string query, Option<List<string>> filterSearchIndex, Option<List<string>> fieldsItem, Option<List<string>> filterTypeNameId)
        {
            if (language == null)
                throw new ArgumentNullException(nameof(language));

            if (game == null)
                throw new ArgumentNullException(nameof(game));

            if (query == null)
                throw new ArgumentNullException(nameof(query));

            if (filterSearchIndex.IsSet && filterSearchIndex.Value == null)
                throw new ArgumentNullException(nameof(filterSearchIndex));

            if (fieldsItem.IsSet && fieldsItem.Value == null)
                throw new ArgumentNullException(nameof(fieldsItem));

            if (filterTypeNameId.IsSet && filterTypeNameId.Value == null)
                throw new ArgumentNullException(nameof(filterTypeNameId));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="language"></param>
        /// <param name="game"></param>
        /// <param name="query"></param>
        /// <param name="filterSearchIndex"></param>
        /// <param name="limit"></param>
        /// <param name="fieldsItem"></param>
        /// <param name="filterTypeNameId"></param>
        private void AfterGetGameSearchDefaultImplementation(IGetGameSearchApiResponse apiResponseLocalVar, string language, string game, string query, Option<List<string>> filterSearchIndex, Option<int> limit, Option<List<string>> fieldsItem, Option<List<string>> filterTypeNameId)
        {
            bool suppressDefaultLog = false;
            AfterGetGameSearch(ref suppressDefaultLog, apiResponseLocalVar, language, game, query, filterSearchIndex, limit, fieldsItem, filterTypeNameId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="language"></param>
        /// <param name="game"></param>
        /// <param name="query"></param>
        /// <param name="filterSearchIndex"></param>
        /// <param name="limit"></param>
        /// <param name="fieldsItem"></param>
        /// <param name="filterTypeNameId"></param>
        partial void AfterGetGameSearch(ref bool suppressDefaultLog, IGetGameSearchApiResponse apiResponseLocalVar, string language, string game, string query, Option<List<string>> filterSearchIndex, Option<int> limit, Option<List<string>> fieldsItem, Option<List<string>> filterTypeNameId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="language"></param>
        /// <param name="game"></param>
        /// <param name="query"></param>
        /// <param name="filterSearchIndex"></param>
        /// <param name="limit"></param>
        /// <param name="fieldsItem"></param>
        /// <param name="filterTypeNameId"></param>
        private void OnErrorGetGameSearchDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string language, string game, string query, Option<List<string>> filterSearchIndex, Option<int> limit, Option<List<string>> fieldsItem, Option<List<string>> filterTypeNameId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetGameSearch(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, language, game, query, filterSearchIndex, limit, fieldsItem, filterTypeNameId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="language"></param>
        /// <param name="game"></param>
        /// <param name="query"></param>
        /// <param name="filterSearchIndex"></param>
        /// <param name="limit"></param>
        /// <param name="fieldsItem"></param>
        /// <param name="filterTypeNameId"></param>
        partial void OnErrorGetGameSearch(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string language, string game, string query, Option<List<string>> filterSearchIndex, Option<int> limit, Option<List<string>> fieldsItem, Option<List<string>> filterTypeNameId);

        /// <summary>
        /// Game Search Search in all names and descriptions of all supported types in the game. For the list of supported types see the endpoint /dofus3/meta/search/types.
        /// </summary>
        /// <param name="language">a valid language code</param>
        /// <param name="game">game main &#39;dofus3&#39; or beta channel &#39;dofus3beta&#39;</param>
        /// <param name="query">search query</param>
        /// <param name="filterSearchIndex">only results with all specific type (optional)</param>
        /// <param name="limit">maximum number of returned results (optional, default to 8)</param>
        /// <param name="fieldsItem">adds fields from the item search to the list entries if the hit is an item. Multiple comma separated values allowed. (optional)</param>
        /// <param name="filterTypeNameId">multi-filter results with the english item type name, including \&quot;mount\&quot; and \&quot;set\&quot; from filter[search_index]. Add with \&quot;wood\&quot; or \&quot;+wood\&quot; and exclude with \&quot;-wood\&quot;. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetGameSearchApiResponse"/>&gt;</returns>
        public async Task<IGetGameSearchApiResponse?> GetGameSearchOrDefaultAsync(string language, string game, string query, Option<List<string>> filterSearchIndex = default, Option<int> limit = default, Option<List<string>> fieldsItem = default, Option<List<string>> filterTypeNameId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetGameSearchAsync(language, game, query, filterSearchIndex, limit, fieldsItem, filterTypeNameId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Game Search Search in all names and descriptions of all supported types in the game. For the list of supported types see the endpoint /dofus3/meta/search/types.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="language">a valid language code</param>
        /// <param name="game">game main &#39;dofus3&#39; or beta channel &#39;dofus3beta&#39;</param>
        /// <param name="query">search query</param>
        /// <param name="filterSearchIndex">only results with all specific type (optional)</param>
        /// <param name="limit">maximum number of returned results (optional, default to 8)</param>
        /// <param name="fieldsItem">adds fields from the item search to the list entries if the hit is an item. Multiple comma separated values allowed. (optional)</param>
        /// <param name="filterTypeNameId">multi-filter results with the english item type name, including \&quot;mount\&quot; and \&quot;set\&quot; from filter[search_index]. Add with \&quot;wood\&quot; or \&quot;+wood\&quot; and exclude with \&quot;-wood\&quot;. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetGameSearchApiResponse"/>&gt;</returns>
        public async Task<IGetGameSearchApiResponse> GetGameSearchAsync(string language, string game, string query, Option<List<string>> filterSearchIndex = default, Option<int> limit = default, Option<List<string>> fieldsItem = default, Option<List<string>> filterTypeNameId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateGetGameSearch(language, game, query, filterSearchIndex, fieldsItem, filterTypeNameId);

                FormatGetGameSearch(ref language, ref game, ref query, filterSearchIndex, ref limit, fieldsItem, filterTypeNameId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/{game}/v1/{language}/search"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/{game}/v1/{language}/search");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Blanguage%7D", Uri.EscapeDataString(language.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bgame%7D", Uri.EscapeDataString(game.ToString()));

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    parseQueryStringLocalVar["query"] = ClientUtils.ParameterToString(query);

                    if (filterSearchIndex.IsSet)
                        parseQueryStringLocalVar["filter[search_index]"] = ClientUtils.ParameterToString(filterSearchIndex.Value);

                    if (limit.IsSet)
                        parseQueryStringLocalVar["limit"] = ClientUtils.ParameterToString(limit.Value);

                    if (fieldsItem.IsSet)
                        parseQueryStringLocalVar["fields[item]"] = ClientUtils.ParameterToString(fieldsItem.Value);

                    if (filterTypeNameId.IsSet)
                        parseQueryStringLocalVar["filter[type.name_id]"] = ClientUtils.ParameterToString(filterTypeNameId.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<GetGameSearchApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetGameSearchApiResponse>();

                        GetGameSearchApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/{game}/v1/{language}/search", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterGetGameSearchDefaultImplementation(apiResponseLocalVar, language, game, query, filterSearchIndex, limit, fieldsItem, filterTypeNameId);

                        Events.ExecuteOnGetGameSearch(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetGameSearchDefaultImplementation(e, "/{game}/v1/{language}/search", uriBuilderLocalVar.Path, language, game, query, filterSearchIndex, limit, fieldsItem, filterTypeNameId);
                Events.ExecuteOnErrorGetGameSearch(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetGameSearchApiResponse"/>
        /// </summary>
        public partial class GetGameSearchApiResponse : Dofusdude.Api.Client.ApiResponse, IGetGameSearchApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetGameSearchApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetGameSearchApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetGameSearchApiResponse(ILogger<GetGameSearchApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public List<GameSearch>? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<List<GameSearch>>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out List<GameSearch>? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public Dofusdude.Api.Model.Error? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<Dofusdude.Api.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out Dofusdude.Api.Model.Error? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public Dofusdude.Api.Model.Error? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<Dofusdude.Api.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out Dofusdude.Api.Model.Error? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatGetItemsAllSearch(ref string language, ref string game, ref string query, ref Option<int> filterMinLevel, ref Option<int> filterMaxLevel, ref Option<int> limit, Option<List<string>> filterTypeNameId);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="language"></param>
        /// <param name="game"></param>
        /// <param name="query"></param>
        /// <param name="filterTypeNameId"></param>
        /// <returns></returns>
        private void ValidateGetItemsAllSearch(string language, string game, string query, Option<List<string>> filterTypeNameId)
        {
            if (language == null)
                throw new ArgumentNullException(nameof(language));

            if (game == null)
                throw new ArgumentNullException(nameof(game));

            if (query == null)
                throw new ArgumentNullException(nameof(query));

            if (filterTypeNameId.IsSet && filterTypeNameId.Value == null)
                throw new ArgumentNullException(nameof(filterTypeNameId));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="language"></param>
        /// <param name="game"></param>
        /// <param name="query"></param>
        /// <param name="filterMinLevel"></param>
        /// <param name="filterMaxLevel"></param>
        /// <param name="limit"></param>
        /// <param name="filterTypeNameId"></param>
        private void AfterGetItemsAllSearchDefaultImplementation(IGetItemsAllSearchApiResponse apiResponseLocalVar, string language, string game, string query, Option<int> filterMinLevel, Option<int> filterMaxLevel, Option<int> limit, Option<List<string>> filterTypeNameId)
        {
            bool suppressDefaultLog = false;
            AfterGetItemsAllSearch(ref suppressDefaultLog, apiResponseLocalVar, language, game, query, filterMinLevel, filterMaxLevel, limit, filterTypeNameId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="language"></param>
        /// <param name="game"></param>
        /// <param name="query"></param>
        /// <param name="filterMinLevel"></param>
        /// <param name="filterMaxLevel"></param>
        /// <param name="limit"></param>
        /// <param name="filterTypeNameId"></param>
        partial void AfterGetItemsAllSearch(ref bool suppressDefaultLog, IGetItemsAllSearchApiResponse apiResponseLocalVar, string language, string game, string query, Option<int> filterMinLevel, Option<int> filterMaxLevel, Option<int> limit, Option<List<string>> filterTypeNameId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="language"></param>
        /// <param name="game"></param>
        /// <param name="query"></param>
        /// <param name="filterMinLevel"></param>
        /// <param name="filterMaxLevel"></param>
        /// <param name="limit"></param>
        /// <param name="filterTypeNameId"></param>
        private void OnErrorGetItemsAllSearchDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string language, string game, string query, Option<int> filterMinLevel, Option<int> filterMaxLevel, Option<int> limit, Option<List<string>> filterTypeNameId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorGetItemsAllSearch(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, language, game, query, filterMinLevel, filterMaxLevel, limit, filterTypeNameId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="language"></param>
        /// <param name="game"></param>
        /// <param name="query"></param>
        /// <param name="filterMinLevel"></param>
        /// <param name="filterMaxLevel"></param>
        /// <param name="limit"></param>
        /// <param name="filterTypeNameId"></param>
        partial void OnErrorGetItemsAllSearch(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string language, string game, string query, Option<int> filterMinLevel, Option<int> filterMaxLevel, Option<int> limit, Option<List<string>> filterTypeNameId);

        /// <summary>
        /// Search All Items Search in all names and descriptions of Dofus items (including all subtypes) with a query.
        /// </summary>
        /// <param name="language">a valid language code</param>
        /// <param name="game">game main &#39;dofus3&#39; or beta channel &#39;dofus3beta&#39;</param>
        /// <param name="query">case sensitive search query</param>
        /// <param name="filterMinLevel">only results which level is equal or above this value (optional)</param>
        /// <param name="filterMaxLevel">only results which level is equal or below this value (optional)</param>
        /// <param name="limit">maximum number of returned results (optional, default to 8)</param>
        /// <param name="filterTypeNameId">multi-filter results with the english type name. Add with \&quot;wood\&quot; or \&quot;+wood\&quot; and exclude with \&quot;-wood\&quot;. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetItemsAllSearchApiResponse"/>&gt;</returns>
        public async Task<IGetItemsAllSearchApiResponse?> GetItemsAllSearchOrDefaultAsync(string language, string game, string query, Option<int> filterMinLevel = default, Option<int> filterMaxLevel = default, Option<int> limit = default, Option<List<string>> filterTypeNameId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await GetItemsAllSearchAsync(language, game, query, filterMinLevel, filterMaxLevel, limit, filterTypeNameId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Search All Items Search in all names and descriptions of Dofus items (including all subtypes) with a query.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="language">a valid language code</param>
        /// <param name="game">game main &#39;dofus3&#39; or beta channel &#39;dofus3beta&#39;</param>
        /// <param name="query">case sensitive search query</param>
        /// <param name="filterMinLevel">only results which level is equal or above this value (optional)</param>
        /// <param name="filterMaxLevel">only results which level is equal or below this value (optional)</param>
        /// <param name="limit">maximum number of returned results (optional, default to 8)</param>
        /// <param name="filterTypeNameId">multi-filter results with the english type name. Add with \&quot;wood\&quot; or \&quot;+wood\&quot; and exclude with \&quot;-wood\&quot;. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IGetItemsAllSearchApiResponse"/>&gt;</returns>
        public async Task<IGetItemsAllSearchApiResponse> GetItemsAllSearchAsync(string language, string game, string query, Option<int> filterMinLevel = default, Option<int> filterMaxLevel = default, Option<int> limit = default, Option<List<string>> filterTypeNameId = default, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateGetItemsAllSearch(language, game, query, filterTypeNameId);

                FormatGetItemsAllSearch(ref language, ref game, ref query, ref filterMinLevel, ref filterMaxLevel, ref limit, filterTypeNameId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/{game}/v1/{language}/items/search"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/{game}/v1/{language}/items/search");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Blanguage%7D", Uri.EscapeDataString(language.ToString()));
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bgame%7D", Uri.EscapeDataString(game.ToString()));

                    System.Collections.Specialized.NameValueCollection parseQueryStringLocalVar = System.Web.HttpUtility.ParseQueryString(string.Empty);

                    parseQueryStringLocalVar["query"] = ClientUtils.ParameterToString(query);

                    if (filterMinLevel.IsSet)
                        parseQueryStringLocalVar["filter[min_level]"] = ClientUtils.ParameterToString(filterMinLevel.Value);

                    if (filterMaxLevel.IsSet)
                        parseQueryStringLocalVar["filter[max_level]"] = ClientUtils.ParameterToString(filterMaxLevel.Value);

                    if (limit.IsSet)
                        parseQueryStringLocalVar["limit"] = ClientUtils.ParameterToString(limit.Value);

                    if (filterTypeNameId.IsSet)
                        parseQueryStringLocalVar["filter[type.name_id]"] = ClientUtils.ParameterToString(filterTypeNameId.Value);

                    uriBuilderLocalVar.Query = parseQueryStringLocalVar.ToString();

                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<GetItemsAllSearchApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<GetItemsAllSearchApiResponse>();

                        GetItemsAllSearchApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/{game}/v1/{language}/items/search", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterGetItemsAllSearchDefaultImplementation(apiResponseLocalVar, language, game, query, filterMinLevel, filterMaxLevel, limit, filterTypeNameId);

                        Events.ExecuteOnGetItemsAllSearch(apiResponseLocalVar);

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorGetItemsAllSearchDefaultImplementation(e, "/{game}/v1/{language}/items/search", uriBuilderLocalVar.Path, language, game, query, filterMinLevel, filterMaxLevel, limit, filterTypeNameId);
                Events.ExecuteOnErrorGetItemsAllSearch(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="GetItemsAllSearchApiResponse"/>
        /// </summary>
        public partial class GetItemsAllSearchApiResponse : Dofusdude.Api.Client.ApiResponse, IGetItemsAllSearchApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<GetItemsAllSearchApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="GetItemsAllSearchApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public GetItemsAllSearchApiResponse(ILogger<GetItemsAllSearchApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public List<ListItemGeneral>? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<List<ListItemGeneral>>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out List<ListItemGeneral>? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public Dofusdude.Api.Model.Error? BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<Dofusdude.Api.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out Dofusdude.Api.Model.Error? result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public Dofusdude.Api.Model.Error? NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<Dofusdude.Api.Model.Error>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out Dofusdude.Api.Model.Error? result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
